language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

install:
 - pip install -e .
 - pip install -r requirements-dev.txt

script:
  - flake8 src/
  - python setup.py test

notifications:
  email:
    - tomaz+travisci@tomaz.me
